-- ════════════════════════════════════════════════════════════════════════════
-- 0007 · Metric catalog seed (global reference data).
-- Reference ranges & flag thresholds from preventive-medicine guidelines
-- (ADA 2024, ACC/AHA 2017 BP, NLA/ESC ApoB & Lp(a), CKD-EPI 2021). These are
-- general adult values for color-coding ONLY — the lab's own printed range
-- overrides on import, and none of this constitutes medical advice.
--
-- Flag bands:  value <= flag_low_red  OR value >= flag_high_red   -> red
--              value <= flag_low_yellow OR value >= flag_high_yellow -> yellow
--              else green   (nulls = unbounded on that side)
-- ════════════════════════════════════════════════════════════════════════════

insert into metrics
  (id, display_name, panel, canonical_unit, loinc_code, direction,
   ref_low, ref_high, optimal_low, optimal_high,
   flag_low_red, flag_low_yellow, flag_high_yellow, flag_high_red,
   sex_specific, fasting_required, cadence_days, hero, notes) values
-- ── Cardiometabolic / Lipids ────────────────────────────────────────────────
('apob','Apolipoprotein B','lipids','mg/dL','1884-6','lower_better',
   null,100, null,80,  null,null,80,100, false,false,365,true,
   'Best single causal marker of atherogenic particle count. Primary-prevention target <80.'),
('ldl_c','LDL Cholesterol','lipids','mg/dL','13457-7','lower_better',
   null,100, null,100, null,null,100,160, false,true,365,false,null),
('hdl_c','HDL Cholesterol','lipids','mg/dL','2085-9','higher_better',
   40,null, 50,80,  40,50,90,null, true,true,365,false,
   'Protective up to a point; very high HDL is not clearly beneficial.'),
('triglycerides','Triglycerides','lipids','mg/dL','2571-8','lower_better',
   null,150, null,100, null,null,100,150, false,true,365,false,
   '>=500 carries pancreatitis risk; invalidates Friedewald LDL >=400.'),
('lpa','Lipoprotein(a)','lipids','nmol/L','43583-5','lower_better',
   null,75, null,75, null,null,75,125, false,false,null,true,
   'Largely genetic; test once per lifetime. >=125 nmol/L high risk.'),
('total_cholesterol','Total Cholesterol','lipids','mg/dL','2093-3','lower_better',
   null,200, null,null, null,null,200,240, false,true,365,false,null),
('non_hdl_c','Non-HDL Cholesterol','lipids','mg/dL','43396-1','lower_better',
   null,130, null,100, null,null,100,160, false,true,365,false,
   'Total cholesterol minus HDL; good atherogenic proxy when ApoB unavailable.'),
('tg_hdl_ratio','Triglyceride : HDL Ratio','lipids','ratio',null,'lower_better',
   null,null, null,2, null,null,2,3, false,true,365,false,'Insulin-resistance surrogate.'),
('remnant_c','Remnant Cholesterol','lipids','mg/dL',null,'lower_better',
   null,30, null,20, null,null,24,30, false,true,365,false,'TC - HDL - LDL.'),
-- ── Metabolic / Glycemic ────────────────────────────────────────────────────
('glucose_fasting','Fasting Glucose','metabolic','mg/dL','1558-6','target_band',
   70,99, 70,90, 69,null,100,126, false,true,365,true,'IFG 100-125; diabetes >=126.'),
('hba1c','Hemoglobin A1c','metabolic','%','4548-4','lower_better',
   null,5.6, null,5.4, null,null,5.7,6.5, false,false,365,true,
   'Prediabetes 5.7-6.4; diabetes >=6.5 (ADA).'),
('insulin_fasting','Fasting Insulin','metabolic','uIU/mL','20448-7','lower_better',
   2,25, 2,6, null,null,7,13, false,true,365,false,null),
('homa_ir','HOMA-IR','metabolic','index',null,'lower_better',
   null,2.0, null,1.5, null,null,1.5,3.0, false,true,365,false,
   '(glucose x insulin)/405. Insulin-resistance index.'),
-- ── Inflammation ────────────────────────────────────────────────────────────
('hs_crp','hs-CRP','inflammation','mg/L','30522-7','lower_better',
   null,3.0, null,1.0, null,null,1.0,3.0, false,false,365,false,
   '>10 usually acute infection, not CV risk — recheck.'),
('homocysteine','Homocysteine','inflammation','umol/L','13965-9','lower_better',
   5,15, null,9, null,null,9,15, false,false,null,false,null),
('uric_acid','Uric Acid','inflammation','mg/dL','3084-1','lower_better',
   2.4,7.0, null,6.0, null,null,6,7, true,false,null,false,null),
-- ── Body composition ────────────────────────────────────────────────────────
('weight','Weight','body','kg','29463-7','target_band',
   null,null, null,null, null,null,null,null, false,false,null,false,'Trend vs personal baseline.'),
('bmi','BMI','body','kg/m2','39156-5','target_band',
   18.5,24.9, 20,25, 18.5,null,25,30, false,false,null,false,null),
('waist_cm','Waist Circumference','body','cm','8280-0','lower_better',
   null,102, null,94, null,null,94,102, true,false,null,false,'Male defaults; female via reference_ranges.'),
('waist_height_ratio','Waist : Height Ratio','body','ratio',null,'lower_better',
   null,0.5, null,0.5, null,null,0.5,0.6, false,false,null,false,null),
('body_fat_pct','Body Fat %','body','%','41982-0','target_band',
   8,25, 10,20, null,null,25,30, true,false,null,false,null),
-- ── Blood pressure & resting HR ─────────────────────────────────────────────
('bp_systolic','Systolic BP','vital','mmHg','8480-6','target_band',
   90,120, null,120, 90,null,120,140, false,false,null,true,'ACC/AHA 2017 categories.'),
('bp_diastolic','Diastolic BP','vital','mmHg','8462-4','target_band',
   60,80, null,80, 60,null,80,90, false,false,null,true,null),
('resting_hr','Resting Heart Rate','vital','bpm','40443-4','lower_better',
   50,100, 50,65, 45,null,66,100, false,false,null,false,null),
-- ── Kidney ──────────────────────────────────────────────────────────────────
('egfr','eGFR (CKD-EPI 2021)','kidney','mL/min/1.73m2','98979-8','higher_better',
   90,null, 90,null, 59,89,null,null, false,false,365,false,'Race-free CKD-EPI creatinine. <60 flags CKD.'),
('creatinine','Creatinine','kidney','mg/dL','2160-0','target_band',
   0.59,1.35, null,null, 0.5,0.59,1.35,1.6, true,false,365,false,null),
('bun','BUN','kidney','mg/dL','3094-0','target_band',
   7,20, 8,18, null,5,20,30, false,false,365,false,null),
('uacr','Urine Albumin:Creatinine','kidney','mg/g','9318-7','lower_better',
   null,30, null,10, null,null,10,30, false,false,365,false,null),
-- ── Liver ───────────────────────────────────────────────────────────────────
('alt','ALT','liver','U/L','1742-6','lower_better',
   7,55, null,25, null,null,25,55, true,false,365,false,'Lower optimal reflects NAFLD sensitivity.'),
('ast','AST','liver','U/L','1920-8','lower_better',
   8,48, null,25, null,null,25,48, false,false,365,false,null),
('ggt','GGT','liver','U/L','2324-2','lower_better',
   null,55, null,25, null,null,25,55, true,false,365,false,null),
('alp','Alkaline Phosphatase','liver','U/L','6768-6','target_band',
   40,129, null,null, null,38,129,160, false,false,365,false,null),
('albumin','Albumin','liver','g/dL','1751-7','higher_better',
   3.5,5.0, 4.0,5.0, 3.2,3.5,null,null, false,false,365,false,null),
('bilirubin_total','Total Bilirubin','liver','mg/dL','1975-2','target_band',
   0.1,1.2, null,null, null,null,1.2,2.0, false,false,365,false,null),
-- ── Thyroid ─────────────────────────────────────────────────────────────────
('tsh','TSH','thyroid','mIU/L','3016-3','target_band',
   0.4,4.0, 0.5,2.5, 0.4,0.5,2.5,4.0, false,false,365,false,null),
('free_t4','Free T4','thyroid','ng/dL','3024-7','target_band',
   0.8,1.8, null,null, null,0.8,1.8,2.2, false,false,365,false,null),
('free_t3','Free T3','thyroid','pg/mL','3051-0','target_band',
   2.3,4.2, null,null, null,2.3,4.2,4.8, false,false,365,false,null),
-- ── CBC ─────────────────────────────────────────────────────────────────────
('hemoglobin','Hemoglobin','cbc','g/dL','718-7','target_band',
   12.0,17.5, null,null, 11,12,17.5,19, true,false,365,false,null),
('hematocrit','Hematocrit','cbc','%','4544-3','target_band',
   36,50, null,null, 33,36,50,54, true,false,365,false,null),
('wbc','White Blood Cells','cbc','10^3/uL','6690-2','target_band',
   4.0,11.0, null,null, 2,4,11,15, false,false,365,false,null),
('platelets','Platelets','cbc','10^3/uL','777-3','target_band',
   150,400, null,null, 100,150,400,500, false,false,365,false,null),
('rdw','RDW','cbc','%','788-0','lower_better',
   11.5,14.5, null,13, null,null,14.5,15.5, false,false,365,false,'Elevated RDW is a mortality signal.'),
('mcv','MCV','cbc','fL','787-2','target_band',
   80,100, null,null, null,80,100,105, false,false,365,false,null),
-- ── Vitamins / minerals ─────────────────────────────────────────────────────
('vitamin_d','Vitamin D (25-OH)','vitamins','ng/mL','62292-8','target_band',
   30,100, 40,60, 20,30,100,null, false,false,365,false,null),
('vitamin_b12','Vitamin B12','vitamins','pg/mL','2132-9','higher_better',
   200,900, 400,800, 200,400,null,null, false,false,365,false,null),
('folate','Folate','vitamins','ng/mL','2284-8','higher_better',
   4,null, 5,null, 4,5,null,null, false,false,365,false,null),
('ferritin','Ferritin','vitamins','ng/mL','2276-4','target_band',
   15,200, 50,150, 30,50,300,400, true,false,365,false,
   'High ferritin = overload OR inflammation; cross-check hs-CRP.'),
('magnesium','Magnesium','vitamins','mg/dL','19123-9','higher_better',
   1.7,2.4, 2.0,2.4, 1.7,2.0,null,null, false,false,365,false,null),
('omega3_index','Omega-3 Index','vitamins','%',null,'higher_better',
   4,null, 8,null, 4,8,null,null, false,false,365,false,null),
-- ── Hormones ────────────────────────────────────────────────────────────────
('testosterone_total','Total Testosterone','hormones','ng/dL','2986-8','higher_better',
   300,1000, 500,900, 300,500,null,null, true,false,365,false,'Male-oriented bands.'),
('free_testosterone','Free Testosterone','hormones','pg/mL','2991-8','higher_better',
   50,200, null,null, 50,70,null,null, true,false,365,false,null),
('psa','PSA','hormones','ng/mL','2857-1','lower_better',
   null,4.0, null,2.5, null,null,2.5,4.0, true,false,365,false,'Velocity >0.75/yr also flags.'),
('cortisol_am','Cortisol (AM)','hormones','ug/dL','2143-6','target_band',
   6,18, null,null, null,6,18,22, false,false,null,false,null),
('igf1','IGF-1','hormones','ng/mL','2484-4','target_band',
   null,null, null,null, null,null,null,null, false,false,null,false,'Age-banded; J-shaped risk.'),
('shbg','SHBG','hormones','nmol/L','13967-5','target_band',
   20,60, null,null, null,20,60,80, false,false,null,false,null),
-- ── Wearable-derived ────────────────────────────────────────────────────────
('hrv_rmssd','HRV (RMSSD)','wearable','ms',null,'higher_better',
   20,null, null,null, null,null,null,null, false,false,null,true,
   'Flag on personal baseline deviation, not absolute cutoffs.'),
('resting_hr_wearable','Resting HR (wearable)','wearable','bpm',null,'lower_better',
   48,80, 48,60, null,null,61,81, false,false,null,false,null),
('vo2max','VO2 Max','wearable','mL/kg/min',null,'higher_better',
   35,null, 48,null, 30,42,null,null, false,false,null,true,
   'Strong all-cause-mortality gradient; aim for top quartile for age/sex.'),
('sleep_duration','Sleep Duration','sleep','hr',null,'target_band',
   7,9, 7,8.5, 6,7,9,10, false,false,null,false,null),
('sleep_efficiency','Sleep Efficiency','sleep','%',null,'higher_better',
   85,null, 90,null, 80,85,null,null, false,false,null,false,null),
('steps','Steps','activity','count',null,'higher_better',
   null,null, 8000,null, 5000,7000,null,null, false,false,null,false,'Mortality benefit plateaus ~8-10k.'),
('active_energy','Active Energy','activity','kcal',null,'higher_better',
   null,null, null,null, null,null,null,null, false,false,null,false,'Trend vs baseline.'),
('respiratory_rate','Respiratory Rate','wearable','breaths/min',null,'target_band',
   12,20, 12,16, null,12,20,24, false,false,null,false,'Sudden change can signal illness.')
on conflict (id) do update set
  display_name=excluded.display_name, panel=excluded.panel,
  canonical_unit=excluded.canonical_unit, loinc_code=excluded.loinc_code,
  direction=excluded.direction, ref_low=excluded.ref_low, ref_high=excluded.ref_high,
  optimal_low=excluded.optimal_low, optimal_high=excluded.optimal_high,
  flag_low_red=excluded.flag_low_red, flag_low_yellow=excluded.flag_low_yellow,
  flag_high_yellow=excluded.flag_high_yellow, flag_high_red=excluded.flag_high_red,
  sex_specific=excluded.sex_specific, fasting_required=excluded.fasting_required,
  cadence_days=excluded.cadence_days, hero=excluded.hero, notes=excluded.notes;
